name: PushDockerImage
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.11'
    - name: download csv
      run: |
        cd sentiment_model/datasets
        wget -q https://cdn.iisc.talentsprint.com/AIandMLOps/MiniProjects/Datasets/Reviews.csv
        ls | grep ".csv"     
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train 
      run: python sentiment_model/train_model.py
    - name: ls
      run: ls -lrt
    - name: Predict
      run: python sentiment_model/predict.py
    - uses: actions/upload-artifact@v2
      with:
        name: my-trained-sentiment-model
        path: sentiment_model/trained_models/*.pkl
        retention-days: 1
    - uses: actions/upload-artifact@v2
      with:
        name: my-trained-tokenizer
        path: sentiment_model/trained_tokenizer/*.json
        retention-days: 1
    - name: ls
      run: ls -lrt    
 
  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-sentiment-model
    - run: mv *.pkl sentiment_model/trained_models/
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-tokenizer
    - run: mv *.json sentiment_model/trained_tokenizer/
    - name: Install dependencies
      run: pip install -r requirements/test_requirements.txt
    - name: Test with pytest
      run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-sentiment-model
    - run: mv *.pkl sentiment_model/trained_models/
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-tokenizer
    - run: mv *.json sentiment_model/trained_tokenizer/
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: |
        pip install --upgrade build
        python -m build
    - uses: actions/upload-artifact@v2
      with:
        name: my-build-package
        path: dist/*.whl
        retention-days: 1

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: my-build-package
    - run: mv *.whl sentiment_model_api/

    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/sentiment-fastapi:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker push $DOCKER_USER/sentiment-fastapi

    - name: Logout to Docker hub
      run: docker logout
